locals {
  cis_v110_1_common_tags = merge(local.cis_v110_common_tags, {
    cis_section_id = "1"
  })
}

benchmark "cis_v110_1" {
  title         = "1 Identity and Access Management"
  documentation = file("./cis_v110/docs/cis_v110_1.md")
  children = [
    control.cis_v110_1_1,
    control.cis_v110_1_4,
    control.cis_v110_1_7,
    control.cis_v110_1_8,
    control.cis_v110_1_9,
    control.cis_v110_1_10,
    control.cis_v110_1_11,
    control.cis_v110_1_12,
  ]

  tags = merge(local.cis_v110_1_common_tags, {
    service = "OCI/Identity"
    type    = "Benchmark"
  })
}

control "cis_v110_1_1" {
  title         = "1.1 Ensure service level admins are created to manage resources of particular service"
  description   = "To apply least-privilege security principle, one can create service-level administrators in corresponding groups and assigning specific users to each service-level administrative group in a tenancy. This limits administrative access in a tenancy."
  sql           = query.manual_control.sql
  documentation = file("./cis_v110/docs/cis_v110_1_1.md")

  tags = merge(local.cis_v110_1_common_tags, {
    cis_item_id = "1.1"
    cis_level   = "1"
    cis_type    = "manual"
    service     = "OCI/Identity"
  })
}

control "cis_v110_1_4" {
  title         = "1.4 Ensure IAM password policy requires minimum length of 14 or greater"
  description   = "Password policies are used to enforce password complexity requirements. IAM password policies can be used to ensure password are at least a certain length and are composed of certain characters. It is recommended the password policy require a minimum password length 14 characters and contain 1 non-alphabetic character (Number or 'Special Character')."
  sql           = query.identity_authentication_password_policy_strong_min_length_14.sql
  documentation = file("./cis_v110/docs/cis_v110_1_4.md")

  tags = merge(local.cis_v110_1_common_tags, {
    cis_item_id = "1.4"
    cis_level   = "1"
    cis_type    = "manual"
    service     = "OCI/Identity"
  })
}

control "cis_v110_1_7" {
  title         = "1.7 Ensure MFA is enabled for all users with a console password"
  description   = "Multi-factor authentication is a method of authentication that requires the use of more than one factor to verify a user’s identity."
  sql           = query.identity_user_console_access_mfa_enabled.sql
  documentation = file("./cis_v110/docs/cis_v110_1_7.md")

  tags = merge(local.cis_v110_1_common_tags, {
    cis_item_id = "1.7"
    cis_level   = "1"
    cis_type    = "automated"
    service     = "OCI/Identity"
  })
}

control "cis_v110_1_8" {
  title         = "1.8 Ensure user API keys rotate within 90 days or less"
  description   = "API keys are used by administrators, developers, services and scripts for accessing OCI APIs directly or via SDKs/OCI CLI to search, create, update or delete OCI resources. The API key is an RSA key pair. The private key is used for signing the API requests and the public key is associated with a local or synchronized user's profile."
  sql           = query.identity_user_api_key_age_90.sql
  documentation = file("./cis_v110/docs/cis_v110_1_8.md")

  tags = merge(local.cis_v110_1_common_tags, {
    cis_item_id = "1.8"
    cis_level   = "1"
    cis_type    = "automated"
    service     = "OCI/Identity"
  })
}

control "cis_v110_1_9" {
  title         = "1.9 Ensure user customer secret keys rotate within 90 days or less"
  description   = "Object Storage provides an API to enable interoperability with Amazon S3. To use this Amazon S3 Compatibility API, you need to generate the signing key required to authenticate with Amazon S3. This special signing key is an Access Key/Secret Key pair. Oracle generates the Customer Secret key to pair with the Access Key."
  sql           = query.identity_user_customer_secret_key_age_90.sql
  documentation = file("./cis_v110/docs/cis_v110_1_9.md")

  tags = merge(local.cis_v110_1_common_tags, {
    cis_item_id = "1.9"
    cis_level   = "1"
    cis_type    = "automated"
    service     = "OCI/Identity"
  })
}

control "cis_v110_1_10" {
  title         = "1.10 Ensure user auth tokens rotate within 90 days or less"
  description   = "Auth tokens are authentication tokens generated by Oracle. You use auth tokens to authenticate with APIs that do not support the Oracle Cloud Infrastructure signature-based authentication. If the service requires an auth token, the service-specific documentation instructs you to generate one and how to use it."
  sql           = query.identity_auth_token_age_90.sql
  documentation = file("./cis_v110/docs/cis_v110_1_10.md")

  tags = merge(local.cis_v110_1_common_tags, {
    cis_item_id = "1.10"
    cis_level   = "1"
    cis_type    = "automated"
    service     = "OCI/Identity"
  })
}

control "cis_v110_1_11" {
  title         = "1.11 Ensure API keys are not created for tenancy administrator users"
  description   = "Tenancy administrator users have full access to the organization's OCI tenancy. API keys associated with user accounts are used for invoking the OCI APIs via custom programs or clients like CLI/SDKs."
  sql           = query.identity_administrator_user_with_no_api_key.sql
  documentation = file("./cis_v110/docs/cis_v110_1_11.md")

  tags = merge(local.cis_v110_1_common_tags, {
    cis_item_id = "1.11"
    cis_level   = "1"
    cis_type    = "automated"
    service     = "OCI/Identity"
  })
}

control "cis_v110_1_12" {
  title         = "1.12 Ensure all OCI IAM user accounts have a valid and current email address"
  description   = "All OCI IAM local user accounts have an email address field associated with the account. It is recommended to specify an email address that is valid and current."
  sql           = query.identity_user_valid_email.sql
  documentation = file("./cis_v110/docs/cis_v110_1_12.md")

  tags = merge(local.cis_v110_1_common_tags, {
    cis_item_id = "1.12"
    cis_level   = "1"
    cis_type    = "manual"
    service     = "OCI/Identity"
  })
}
